#!/bin/bash
set -euox pipefail

# update-bazelisk.sh
#
# This script automates the process of updating Bazelisk binaries and creating
# a pull request with the changes. It is designed to be run by the
# update-bazelisk.yml GitHub Actions workflow.
#
# The script:
# 1. Updates Bazelisk binaries using the bazel wrapper script
# 2. Checks if any changes were made
# 3. Creates a new branch and commits the changes
# 4. Pushes the branch and creates a pull request
#
# Required environment variables (set by GitHub Actions):
#   GITHUB_TOKEN: GitHub token for creating PRs (via gh CLI)

./bazel --update-bazelisk

if git diff --quiet tools/bazelisk-*; then
  echo "No changes detected - Bazelisk is already up to date"
  exit 0
fi

echo "Changes detected - proceeding with commit and PR creation"

# Capture full output first, then extract version to avoid SIGPIPE with `set -o pipefail`
BAZELISK_OUTPUT=$(./tools/bazelisk-linux-amd64 version)
NEW_VERSION=$(echo "$BAZELISK_OUTPUT" | awk '/^Bazelisk version:/ {print $3; exit}')
echo "New Bazelisk version: $NEW_VERSION"

git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"

BRANCH_NAME="chore/update-bazelisk-${NEW_VERSION}"
git checkout -b "$BRANCH_NAME"
git add tools/bazelisk-*

git commit -m "$(cat <<EOF
chore: update Bazelisk to ${NEW_VERSION}

Problem
================================================================================

Bazelisk binaries need to be kept up-to-date to ensure compatibility with the
latest Bazel releases and to receive security updates and bug fixes.

Context
================================================================================

What was the previous state?
--------------------------------------------------------------------------------

The repository was using an older version of Bazelisk. A new release
(${NEW_VERSION}) is now available with potential improvements and fixes.

Solution
================================================================================

Update all Bazelisk binaries (linux-amd64, linux-arm64, darwin-amd64,
darwin-arm64, windows-amd64, windows-arm64) to ${NEW_VERSION} by running the
automated update script.

Rationale
================================================================================

Why automate this update?
--------------------------------------------------------------------------------

Keeping all platform binaries at the same version ensures consistent behavior
across development environments and simplifies version tracking.
EOF
)"

git push origin "$BRANCH_NAME"
gh pr create \
  --title "chore: update Bazelisk to ${NEW_VERSION}" \
  --body "$(cat <<EOF
## Summary

- Updates Bazelisk binaries to ${NEW_VERSION}

🤖 Automated update generated by [update-bazelisk.yml](.github/workflows/update-bazelisk.yml)
EOF
)" \
  --base main \
  --head "$BRANCH_NAME"
