#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

LINUX_BUILD="/tmp/linux-build"
mkdir -p ${LINUX_BUILD}
cd ${LINUX_BUILD}

make -C ${LINUX_SOURCE} \
    HOSTCC=gcc \
    CROSS_COMPILE=x86_64-linux-musl- \
    O=${LINUX_BUILD} \
    ARCH=x86 \
    INSTALL_HDR_PATH=${BUILD_TOOLS}/usr \
    V=0 \
    headers_install
