#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

DATE=$(date +%Y%m%d)

cd "${MUSL_ARTIFACTS}"
XZ_OPT=-e9 tar -cJf "${ARTIFACTS_DIR}/${BUILD_ARCH}-linux-musl-musl-${MUSL_VERSION}-${DATE}.tar.xz" *
