#!/bin/bash
set -euox pipefail

sudo apt-get update
sudo apt-get install -y \
    build-essential \
    wget \
    curl \
    texinfo \
    bison \
    flex \
    gawk \
    m4 \
    python3 \
    xz-utils \
    rsync \
    file \
    autoconf \
    automake \
    libtool
