#!/bin/bash
set -euox pipefail

# Matrix variables from workflow
export GCC_VERSION="${GCC_VERSION}"
export GLIBC_VERSION="${GLIBC_VERSION}"

export OUTPUT_DIR="/tmp/output"
export SYSROOT_DIR="${OUTPUT_DIR}/x86_64-linux-gnu/sysroot"
export BUILD_TOOLS="/tmp/buildtools"

# idk why but crosstool-ng creates these at the beginning
mkdir -p ${OUTPUT_DIR}
mkdir -p ${OUTPUT_DIR}/x86_64-linux-gnu/debug-root
mkdir -p ${OUTPUT_DIR}/lib

mkdir -p ${SYSROOT_DIR}
mkdir -p ${SYSROOT_DIR}/usr/include
mkdir -p ${SYSROOT_DIR}/lib
mkdir -p ${SYSROOT_DIR}/usr/lib

# ==============================
# || Setup Source Directories ||
# ==============================
export ARTIFACTS_DIR="/tmp/artifacts"
export BINUTILS_SOURCE="/tmp/binutils-source"
export EXPAT_SOURCE="/tmp/expat-source"
export GCC_ARTIFACTS="/tmp/gcc-artifacts"
export GCC_SOURCE="/tmp/gcc-source"
export GLIBC_SOURCE="/tmp/glibc-source"
export GMP_SOURCE="/tmp/gmp-source"
export ISL_SOURCE="/tmp/isl-source"
export LINUX_SOURCE="/tmp/linux-source"
export MPC_SOURCE="/tmp/mpc-source"
export MPFR_SOURCE="/tmp/mpfr-source"
export NCURSES_SOURCE="/tmp/ncurses-source"
export ZLIB_SOURCE="/tmp/zlib-source"
export ZSTD_SOURCE="/tmp/zstd-source"

mkdir -p ${ARTIFACTS_DIR}
mkdir -p ${BINUTILS_SOURCE}
mkdir -p ${EXPAT_SOURCE}
mkdir -p ${GCC_SOURCE}
mkdir -p ${GCC_ARTIFACTS}
mkdir -p ${GLIBC_SOURCE}
mkdir -p ${GMP_SOURCE}
mkdir -p ${ISL_SOURCE}
mkdir -p ${LINUX_SOURCE}
mkdir -p ${MPC_SOURCE}
mkdir -p ${MPFR_SOURCE}
mkdir -p ${NCURSES_SOURCE}
mkdir -p ${ZLIB_SOURCE}
mkdir -p ${ZSTD_SOURCE}

if [ -n "${GITHUB_ENV:-}" ]; then
    echo "ARTIFACTS_DIR=${ARTIFACTS_DIR}" >> "${GITHUB_ENV}"
fi
