#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

pushd "${EXPAT_SOURCE}/expat"

./buildconf.sh

env CC=gcc \
    CFLAGS="-O2 -g -pipe -I${BUILD_TOOLS}/include" \
    CXXFLAGS="-O2 -g -pipe -I${BUILD_TOOLS}/include" \
    LDFLAGS="-L${BUILD_TOOLS}/lib" \
    ./configure \
        --build=x86_64-build_pc-linux-gnu \
        --host=x86_64-build_pc-linux-gnu \
        --prefix="${BUILD_TOOLS}" \
        --disable-shared \
        --enable-static \
        --without-docbook

make -j$(nproc) -l
make install

popd
