#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

ZSTD_BUILD_DIR="/tmp/zstd-build"
mkdir -p ${ZSTD_BUILD_DIR}

pushd "${ZSTD_SOURCE}"

make libzstd.a-nomt-release \
    -j$(nproc) -l \
    -C lib \
    BUILD_DIR="${ZSTD_BUILD_DIR}" \
    CFLAGS="-O2 -g -pipe -I${BUILD_TOOLS}/include" \
    LDFLAGS="-L${BUILD_TOOLS}/lib"

make install-static install-includes \
    -C lib \
    BUILD_DIR="${ZSTD_BUILD_DIR}" \
    PREFIX="${BUILD_TOOLS}"

popd
