#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

TARBALLS="/tmp/tarballs"
mkdir -p ${TARBALLS}

# ==============
# || binutils ||
# ==============
BINUTILS_VERSION="2.45"
BINUTILS_VERSION_UNDERSCORES="${BINUTILS_VERSION//./_}"
git clone --depth 1 \
    --branch "binutils-${BINUTILS_VERSION_UNDERSCORES}-branch" \
    git://sourceware.org/git/binutils-gdb.git "${BINUTILS_SOURCE}"

# ===========
# || expat ||
# ===========
EXPAT_VERSION="2.7.3"
EXPAT_VERSION_UNDERSCORES="${EXPAT_VERSION//./_}"
git clone --depth 1 \
    --branch "R_${EXPAT_VERSION_UNDERSCORES}" \
    https://github.com/libexpat/libexpat.git "${EXPAT_SOURCE}"

# =========
# || gcc ||
# =========
GCC_VERSION_UNDERSCORES="${GCC_VERSION//./_}"
git clone --depth 1 \
    --branch "releases/gcc-${GCC_VERSION}" \
    git://gcc.gnu.org/git/gcc.git "${GCC_SOURCE}"

# ===========
# || glibc ||
# ===========
git clone --depth 1 \
    --branch "glibc-${GLIBC_VERSION}" \
    https://sourceware.org/git/glibc.git "${GLIBC_SOURCE}"

# =========
# || gmp ||
# =========
# gmplib.org is unreliable when running on GitHub Actions runners.
# Downloading from our vendored dependencies release instead.
# See: https://github.com/reutermj/toolchains_cc/releases/tag/dependencies-v1
GMP_TARBALL="${TARBALLS}/gmp.tar.xz"
GMP_VERSION="6.3.0"
GMP_URL="https://github.com/reutermj/toolchains_cc/releases/download/dependencies-v1/gmp-${GMP_VERSION}.tar.xz"
wget -O "${GMP_TARBALL}" "${GMP_URL}"
tar xvf "${GMP_TARBALL}" -C "${GMP_SOURCE}" --strip-components=1

# =========
# || isl ||
# =========
ISL_VERSION="0.27"
git clone --depth 1 \
    --branch "isl-${ISL_VERSION}" \
    https://repo.or.cz/isl.git "${ISL_SOURCE}"

# ===================
# || linux-headers ||
# ===================
LINUX_VERSION="6.12"
git clone --depth 1 \
    --branch "v${LINUX_VERSION}" \
    https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git "${LINUX_SOURCE}"

# =========
# || mpc ||
# =========
MPC_VERSION="1.3.1"
git clone --depth 1 \
    --branch "${MPC_VERSION}" \
    https://gitlab.inria.fr/mpc/mpc.git "${MPC_SOURCE}"

# ==========
# || mpfr ||
# ==========
MPFR_VERSION="4.2.2"
git clone --depth 1 \
    --branch "${MPFR_VERSION}" \
    https://gitlab.inria.fr/mpfr/mpfr.git "${MPFR_SOURCE}"

# =============
# || ncurses ||
# =============
# TODO: does ncurses even use source control?
NCURSES_TARBALL="${TARBALLS}/ncurses.tar.gz"
NCURSES_VERSION="6.5"
NCURSES_URL="https://invisible-mirror.net/archives/ncurses/ncurses-${NCURSES_VERSION}.tar.gz"
wget -O "${NCURSES_TARBALL}" "${NCURSES_URL}"
tar xvf "${NCURSES_TARBALL}" -C "${NCURSES_SOURCE}" --strip-components=1

# ==========
# || zlib ||
# ==========
ZLIB_VERSION="1.3.1"
git clone --depth 1 \
    --branch "v${ZLIB_VERSION}" \
    https://github.com/madler/zlib.git "${ZLIB_SOURCE}"

# ==========
# || zstd ||
# ==========
ZSTD_VERSION="1.5.7"
git clone --depth 1 \
    --branch "v${ZSTD_VERSION}" \
    https://github.com/facebook/zstd.git "${ZSTD_SOURCE}"
