#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

LINUX_BUILD_DIR="/tmp/build-kernel-headers"
mkdir -p "${LINUX_BUILD_DIR}"

pushd "${LINUX_SOURCE}"

make \
    "HOSTCC=gcc" \
    "O=${LINUX_BUILD_DIR}" \
    "ARCH=${LINUX_ARCH}" \
    "INSTALL_HDR_PATH=${SYSROOT_DIR}/usr" \
    "V=0" \
    headers_install

popd
