#!/bin/bash
set -euox pipefail

# ==============================
# || Setup Source Directories ||
# ==============================
export ZLIB_SOURCE="/tmp/zlib-source"
export LLVM_SOURCE="/tmp/llvm-source"

mkdir -p ${ZLIB_SOURCE}
mkdir -p ${LLVM_SOURCE}

# =============================
# || Setup Build Directories ||
# =============================
export ZLIB_DIR="/tmp/zlib"
export LLVM_DIR="/tmp/llvm"

mkdir -p ${ZLIB_DIR}
mkdir -p ${LLVM_DIR}

# ====================
# || GCC Toolchain  ||
# ====================
export GCC_DIR="/tmp/gcc"
export GCC_SYSROOT="${GCC_DIR}"
export GCC_BINS="${GCC_DIR}/bin/"

mkdir -p ${GCC_DIR}

# ==============================
# || Setup Output Directories ||
# ==============================
export ARTIFACTS_DIR="/tmp/artifacts"

mkdir -p ${ARTIFACTS_DIR}

# Ensures that ARTIFACTS_DIR is available to provenance attestation in
# the github actions workflow.
if [ -n "${GITHUB_ENV:-}" ]; then
    echo "ARTIFACTS_DIR=${ARTIFACTS_DIR}" >> "${GITHUB_ENV}"
fi
