#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

pushd ${ARTIFACTS_DIR}

RELEASE_NAME="x86_64-linux-libclang-${LLVM_VERSION}-$(date +%Y%m%d)"

XZ_OPT=-e9 tar cJf "${ARTIFACTS_DIR}/${RELEASE_NAME}.tar.xz" \
    lib/libclang* \
    lib/clang/ \
    include/clang-c/

popd
