#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

TARBALLS="/tmp/tarballs"
mkdir -p ${TARBALLS}

# ==============
# || binutils ||
# ==============
BINUTILS_VERSION_UNDERSCORES="${BINUTILS_VERSION//./_}"
retry_with_backoff "${BINUTILS_SOURCE}" \
    git clone --depth 1 \
        --branch "binutils-${BINUTILS_VERSION_UNDERSCORES}-branch" \
        git://sourceware.org/git/binutils-gdb.git "${BINUTILS_SOURCE}"

# ==========
# || zlib ||
# ==========
ZLIB_VERSION="1.3.1"
retry_with_backoff "${ZLIB_SOURCE}" \
    git clone --depth 1 \
        --branch "v${ZLIB_VERSION}" \
        https://github.com/madler/zlib.git "${ZLIB_SOURCE}"
