#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

if [[ -z "${GITHUB_TOKEN:-}" ]]; then
    echo "GITHUB_TOKEN is not set, exiting"
    exit 0
fi

RELEASE_TAG="binaries"

echo "Uploading artifacts to release ${RELEASE_TAG}"
gh release upload "${RELEASE_TAG}" \
    ${ARTIFACTS_DIR}/*.tar.xz \
    --clobber

echo "Successfully uploaded artifacts to release ${RELEASE_TAG}"
