#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

pushd "${BINUTILS_SOURCE}"

env CC_FOR_BUILD=gcc \
    CFLAGS_FOR_BUILD="-O2 -g -I${BUILD_TOOLS}/include" \
    CXXFLAGS_FOR_BUILD="-O2 -g -I${BUILD_TOOLS}/include" \
    CFLAGS="-O2 -g -pipe -I${BUILD_TOOLS}/include" \
    CXXFLAGS="-O2 -g -pipe -I${BUILD_TOOLS}/include" \
    LDFLAGS="-L${BUILD_TOOLS}/lib" \
    ./configure \
        --target=${TARGET} \
        --prefix="${BINUTILS_ARTIFACTS}" \
        --disable-werror \
        --enable-ld=yes \
        --enable-gold=no \
        --enable-deterministic-archives \
        --disable-multilib \
        --disable-gprofng \
        --disable-sim \
        --disable-gdb \
        --without-debuginfod \
        --disable-nls \
        --without-zstd

make -j$(nproc) -l configure-host
make LDFLAGS="-L${BUILD_TOOLS}/lib -all-static" -j$(nproc) -l
make install

popd
