#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

pushd "${BINUTILS_SOURCE}"

# --disable-gdbserver is required in addition to --disable-gdb
# Without it, binutils-gdb still builds gdbserver by default, causing
# linker errors with the -all-static flag (unrecognized by gcc/g++)

# --with-sysroot=/: enables runtime --sysroot flag in ld without hardcoding
# a specific path. Without this, ld rejects --sysroot with error "this linker
# was not configured to use sysroots"
# https://sourceware.org/binutils/docs-2.40/ld/Options.html
env CC_FOR_BUILD=gcc \
    CFLAGS_FOR_BUILD="-O2 -g -I${BUILD_TOOLS}/include" \
    CXXFLAGS_FOR_BUILD="-O2 -g -I${BUILD_TOOLS}/include" \
    CFLAGS="-O2 -g -pipe -I${BUILD_TOOLS}/include" \
    CXXFLAGS="-O2 -g -pipe -I${BUILD_TOOLS}/include" \
    LDFLAGS="-L${BUILD_TOOLS}/lib" \
    ./configure \
        --target=${TARGET} \
        --prefix="${BINUTILS_ARTIFACTS}" \
        --with-sysroot=/ \
        --disable-werror \
        --enable-ld=yes \
        --enable-gold=no \
        --enable-deterministic-archives \
        --disable-multilib \
        --disable-gprofng \
        --disable-sim \
        --disable-gdb \
        --disable-gdbserver \
        --without-debuginfod \
        --disable-nls \
        --without-zstd

make -j$(nproc) -l configure-host
make LDFLAGS="-L${BUILD_TOOLS}/lib -all-static" -j$(nproc) -l
make install

popd
