#!/bin/bash

sudo apt update
DEBIAN_FRONTEND=noninteractive sudo apt install -y \
    build-essential \
    git \
    ninja-build \
    python3 \
    cmake \
    wget \
    curl

pushd $GCC_DIR
wget https://github.com/reutermj/toolchains_cc/releases/download/x86_64-linux-musl-1.2.5-gcc-15.2.0-20250919/x86_64-linux-musl-1.2.5-gcc-15.2.0-20250919.tar.xz
tar xvf x86_64-linux-musl-1.2.5-gcc-15.2.0-20250919.tar.xz
popd
