#!/bin/sh
# gotta use sh here because alpine doesnt ship with

sudo apk update
sudo apk add \
    bash \
    git \
    coreutils \
    diffutils \
    musl-dev \
    gcc \
    g++ \
    binutils-dev \
    make \
    cmake \
    samurai \
    python3 \
    py3-setuptools \
    libffi-dev \
    openssl-dev \
    ncurses-dev \
    libedit-dev \
    libxml2-dev
