#!/bin/bash
source ${SCRIPTS_DIR}/environment

pushd "${BINUTILS_SOURCE}"

env CC_FOR_BUILD=gcc \
    CFLAGS_FOR_BUILD="-O2 -g -I${BUILD_TOOLS}/include" \
    CXXFLAGS_FOR_BUILD="-O2 -g -I${BUILD_TOOLS}/include" \
    CFLAGS="-O2 -g -pipe -I${BUILD_TOOLS}/include" \
    CXXFLAGS="-O2 -g -pipe -I${BUILD_TOOLS}/include" \
    LDFLAGS="-L${BUILD_TOOLS}/lib" \
    ./configure \
        --build=x86_64-build_pc-linux-gnu \
        --host=x86_64-build_pc-linux-gnu \
        --target=x86_64-linux-gnu \
        --with-sysroot="${SYSROOT_DIR}" \
        --disable-werror \
        --enable-ld=yes \
        --enable-gold=no \
        --enable-deterministic-archives \
        --disable-multilib \
        --disable-gprofng \
        --disable-sim \
        --disable-gdb \
        --without-debuginfod \
        --disable-nls \
        --without-zstd

make -j$(nproc) -l configure-host
make LDFLAGS="-L${BUILD_TOOLS}/lib -all-static" -j$(nproc) -l

# This install is gotten from crosstool-ng.
# ct-ng installs all final components into a single output dir at so that it's easy
# to pick up that single directory as the final toolchain.
# TODO: do we still need this given that we will be packaging each component individually?
make install prefix="${OUTPUT_DIR}"

# Install for use when building gcc
make install prefix="${BUILD_TOOLS}"

# Install for packaging
make install prefix="${BINUTILS_ARTIFACTS}"

popd
