#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

pushd "${GMP_SOURCE}"

env CC_FOR_BUILD=gcc \
    CPP_FOR_BUILD=cpp \
    CC=gcc \
    CFLAGS='-O2 -g -pipe -I${BUILD_TOOLS}/include -std=gnu17 -fexceptions' \
    LDFLAGS='-L${BUILD_TOOLS}/lib' \
    ./configure \
        --build=x86_64-build_pc-linux-gnu \
        --host=x86_64-build_pc-linux-gnu \
        --prefix="${BUILD_TOOLS}" \
        --enable-fft \
        --enable-cxx \
        --disable-shared \
        --enable-static

make -j$(nproc) -l
make install

popd
