#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

LINUX_BUILD_DIR="/tmp/build-kernel-headers"
mkdir -p ${LINUX_BUILD_DIR}

pushd "${LINUX_SOURCE}"

make \
    "HOSTCC=gcc" \
    "CROSS_COMPILE=x86_64-linux-gnu-" \
    "O=${LINUX_BUILD_DIR}" \
    "ARCH=x86" \
    "INSTALL_HDR_PATH=${SYSROOT_DIR}/usr" \
    "V=0" \
    headers_install

popd
