#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

GCC_BUILD_DIR=/tmp/gcc-bootstrap-build/
mkdir -p ${GCC_BUILD_DIR}

pushd "${GCC_BUILD_DIR}"

# TODO: how do we verify that glibc and the final gcc compiler are being built with this toolchain?
# could --with-pkgversion and -v be used to get it from the logs?

env CC_FOR_BUILD=gcc \
    CFLAGS="-O2 -g -I${BUILD_TOOLS}/include" \
    CFLAGS_FOR_BUILD="-O2 -g -I${BUILD_TOOLS}/include" \
    CXXFLAGS="-O2 -g -I${BUILD_TOOLS}/include" \
    CXXFLAGS_FOR_BUILD="-O2 -g -I${BUILD_TOOLS}/include" \
    CFLAGS_FOR_TARGET="-g -O2" \
    CXXFLAGS_FOR_TARGET="-g -O2" \
    LDFLAGS="-L${BUILD_TOOLS}/lib" \
    LDFLAGS_FOR_TARGET="" \
    ${GCC_SOURCE}/configure \
        --build=x86_64-build_pc-linux-gnu \
        --host=x86_64-build_pc-linux-gnu \
        --target=x86_64-linux-gnu \
        --with-local-prefix="${SYSROOT_DIR}" \
        --prefix="${OUTPUT_DIR}" \
        --exec_prefix="${BUILD_TOOLS}" \
        --with-sysroot="${SYSROOT_DIR}" \
        --with-newlib \
        --enable-threads=no \
        --disable-shared \
        --with-pkgversion=crosstool-NG 1.28.0.1_403899e \
        --enable-__cxa_atexit \
        --disable-libgomp \
        --disable-libmudflap \
        --disable-libmpx \
        --disable-libssp \
        --disable-libquadmath \
        --disable-libquadmath-support \
        --disable-libstdcxx \
        --with-gmp="${BUILD_TOOLS}" \
        --with-mpfr="${BUILD_TOOLS}" \
        --with-mpc="${BUILD_TOOLS}" \
        --with-isl="${BUILD_TOOLS}" \
        --enable-lto \
        --enable-target-optspace \
        --with-glibc-version=2.28 \
        --with-linker-hash-style=both \
        --disable-plugin \
        --disable-nls \
        --disable-multilib \
        --enable-languages=c

make -j$(nproc) -l configure-gcc configure-libcpp configure-build-libiberty
make -j$(nproc) -l all-libcpp all-build-libcpp all-build-libiberty
make -j$(nproc) -l configure-libdecnumber
make -j$(nproc) -l -C libdecnumber libdecnumber.a
make -j$(nproc) -l configure-libbacktrace
make -j$(nproc) -l -C libbacktrace
make -j$(nproc) -l -C gcc libgcc.mvars
make -j$(nproc) -l all-gcc all-target-libgcc
make install-gcc install-target-libgcc


# ln -sfv x86_64-linux-gnu-gcc ${BUILD_TOOLS}/bin/x86_64-linux-gnu-cc
# rm -rf sysroot-check
# mkdir -p sysroot-check
# touch sysroot-check/seen sysroot-check/unique
# ln -sfv lib ${SYSROOT_DIR}/lib64
# ln -sfv lib ${SYSROOT_DIR}/usr/lib64

popd
