#!/bin/bash
source ${SCRIPTS_DIR}/environment

if [[ -z "${GITHUB_TOKEN:-}" ]]; then
    echo "GITHUB_TOKEN is not set, exiting"
    exit 0
fi

GCC_FULL_VERSION=$("${GCC_ARTIFACTS}/bin/${TARGET}-gcc" --version | head -n1 | awk '{print $NF}')
RELEASE_NAME=$(cat ${GCC_ARTIFACTS}/release_name)

gh release create "${RELEASE_NAME}" \
    ${ARTIFACTS_DIR}/*.tar.xz \
    --repo=https://github.com/reutermj/toolchains_cc \
    --latest=false \
    --title="${RELEASE_NAME}" \
    --notes="GCC ${GCC_FULL_VERSION} toolchain for ${HOST} host targeting ${TARGET} with glibc ${GLIBC_VERSION}"
