#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

sudo apt update
DEBIAN_FRONTEND=noninteractive sudo apt install -y \
    autoconf \
    automake \
    bison \
    build-essential \
    curl \
    flex \
    git \
    libtool \
    rsync \
    texinfo \
    wget
