#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

pushd "${GCC_ARTIFACTS}"
GCC_FULL_VERSION=$("bin/${TARGET}-gcc" --version | head -n1 | awk '{print $NF}')
DATE=$(date +%Y%m%d)

# Maximum compression for reducing artifacts size. 
# Downside: very slow when compressing, but it's ok because this is a fire and forget workload.
export XZ_OPT=-e9

if [[ "${BOOTSTRAP}" == "true" ]]; then
    # ===========================
    # || Package bootstrap gcc ||
    # ===========================
    tar cJf "${ARTIFACTS_DIR}/x86_64-linux-${TARGET}-gcc-bootstrap-${GCC_FULL_VERSION}-${DATE}.tar.xz" .
else
    # =======================
    # || Package libstdc++ ||
    # =======================
    cp -r share share-libstdcxx

    LIBSTDCXX_FILES=()
    LIBSTDCXX_FILES+=(share-libstdcxx)
    LIBSTDCXX_FILES+=(${TARGET}/include/c++/)
    LIBSTDCXX_FILES+=(${TARGET}/lib64/libitm*)
    LIBSTDCXX_FILES+=(${TARGET}/lib64/libstdc++*)
    LIBSTDCXX_FILES+=(${TARGET}/lib64/libsupc++*)

    tar cJf "${ARTIFACTS_DIR}/${TARGET}-libstdcxx-${GCC_FULL_VERSION}-${DATE}.tar.xz" \
        "${LIBSTDCXX_FILES[@]}"

    rm -rf "${LIBSTDCXX_FILES[@]}"

    # =======================================
    # || Package gcc compiler runtime libs ||
    # =======================================
    cp -r share share-libgcc

    LIBGCC_FILES=()
    LIBGCC_FILES+=(share-libgcc)
    LIBGCC_FILES+=(lib/gcc)
    LIBGCC_FILES+=(${TARGET}/lib64/libgcc*)
    LIBGCC_FILES+=(${TARGET}/lib64/libatomic*)

    tar cJf "${ARTIFACTS_DIR}/${TARGET}-libgcc-${GCC_FULL_VERSION}-${DATE}.tar.xz" \
        "${LIBGCC_FILES[@]}"

    rm -rf "${LIBGCC_FILES[@]}"

    # =================
    # || Package gcc ||
    # =================
    tar cJf "${ARTIFACTS_DIR}/x86_64-linux-${TARGET}-gcc-${GCC_FULL_VERSION}-${DATE}.tar.xz" \
        bin/ \
        lib/ \
        libexec/ \
        share/
fi

popd
