#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

pushd "${GCC_ARTIFACTS}"
GCC_FULL_VERSION=$("bin/${TARGET}-gcc" --version | head -n1 | awk '{print $NF}')
DATE=$(date +%Y%m%d)

# Maximum compression for reducing artifacts size. 
# Downside: very slow when compressing, but it's ok because this is a fire and forget workload.
export XZ_OPT=-e9

if [[ "${BOOTSTRAP}" == "true" ]]; then
    # ===========================
    # || Package bootstrap gcc ||
    # ===========================
    tar cJf "${ARTIFACTS_DIR}/${BUILD_ARCH}-linux-${TARGET}-gcc-${GCC_FULL_VERSION}-${DATE}.tar.xz" .
else
    # =======================
    # || Package gcc libs  ||
    # =======================
    cp -r share share-lib

    tar cJf "${ARTIFACTS_DIR}/${TARGET}-gcc-lib-${GCC_FULL_VERSION}-${DATE}.tar.xz" \
        ${TARGET}/include/c++/ \
        ${TARGET}/lib64/ \
        lib/ \
        share-lib/

    # =================
    # || Package gcc ||
    # =================
    tar cJf "${ARTIFACTS_DIR}/${BUILD_ARCH}-linux-${TARGET}-gcc-${GCC_FULL_VERSION}-${DATE}.tar.xz" \
        bin/ \
        libexec/ \
        share/
fi

popd
