#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

pushd "${GCC_BUILD}"
GCC_FULL_VERSION=$("bin/x86_64-linux-gnu-gcc" --version | head -n1 | awk '{print $NF}')
DATE=$(date +%Y%m%d)

# =======================
# || Package libstdc++ ||
# =======================
cp -r share share-libstdcxx

LIBSTDCXX_FILES=()
LIBSTDCXX_FILES+=(share-libstdcxx)
LIBSTDCXX_FILES+=(include/c++/)
LIBSTDCXX_FILES+=(lib64/libitm*)
LIBSTDCXX_FILES+=(lib64/libstdc++*)
LIBSTDCXX_FILES+=(lib64/libsupc++*)

XZ_OPT=-e9 tar cJf "${ARTIFACTS_DIR}/x86_64-linux-gnu-libstdcxx-${GCC_FULL_VERSION}-${DATE}.tar.xz" \
    "${LIBSTDCXX_FILES[@]}"

rm -rf "${LIBSTDCXX_FILES[@]}"

# =======================================
# || Package gcc compiler runtime libs ||
# =======================================
cp -r share share-libgcc

LIBGCC_FILES=()
LIBGCC_FILES+=(share-libgcc)
LIBGCC_FILES+=(lib/gcc)
LIBGCC_FILES+=(lib64/libgcc*)
LIBGCC_FILES+=(lib64/libatomic*)

XZ_OPT=-e9 tar cJf "${ARTIFACTS_DIR}/x86_64-linux-gnu-libgcc-${GCC_FULL_VERSION}-${DATE}.tar.xz" \
    "${LIBGCC_FILES[@]}"

rm -rf "${LIBGCC_FILES[@]}"

# =================
# || Package gcc ||
# =================
XZ_OPT=-e9 tar cJf "${ARTIFACTS_DIR}/x86_64-linux-x86_64-linux-gnu-gcc-${GCC_FULL_VERSION}-${DATE}.tar.xz" \
    bin/ \
    lib/ \
    libexec/ \
    share/

popd
