# TODO: need to rethink how to handle multiple toolchains in a single build graph
# package(default_visibility = ["//visibility:public"])

# constraint_setting(
#     name = "c++",
#     default_constraint_value = "libstdc++",
# )

# constraint_value(
#     name = "libc++",
#     constraint_setting = ":c++",
# )

# constraint_value(
#     name = "libstdc++",
#     constraint_setting = ":c++",
# )
