#!/bin/bash
set -euox pipefail

# Install newer GitHub CLI for attestation support (requires v2.47.0+)
# Ubuntu package version is too old, so install from GitHub releases
# We can assume the actions runner has a good enough version of gh so we only need it in the dockerfile
GH_VERSION="2.83.2"
wget "https://github.com/cli/cli/releases/download/v${GH_VERSION}/gh_${GH_VERSION}_linux_amd64.tar.gz"
tar -xzf "gh_${GH_VERSION}_linux_amd64.tar.gz"
sudo install "gh_${GH_VERSION}_linux_amd64/bin/gh" /usr/local/bin/gh
