#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

pushd "${GLIBC_ARTIFACTS}"

# Package format: <target>-glibc-<version>-<datetime>.tar.xz
# Example: x86_64-linux-gnu-glibc-2.28-20241130.tar.xz
DATETIME=$(date +%Y%m%d)
PACKAGE_NAME="${TARGET}-glibc-${GLIBC_VERSION}-${DATETIME}.tar.xz"
RELEASE_NAME="glibc-${GLIBC_VERSION}-${DATETIME}"

# Save release name for upload step
echo "${RELEASE_NAME}" > "${ARTIFACTS_DIR}/release_name"

XZ_OPT=-e9 tar cJf "${ARTIFACTS_DIR}/${PACKAGE_NAME}" *

popd
