#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

pushd "${GLIBC_ARTIFACTS}"

mkdir lib
mkdir usr/lib

MESSAGE="See https://github.com/reutermj/toolchains_cc/blob/main/docs/lore/gcc/load_bearing_directories.md"
echo ${MESSAGE} > lib/keep_load_bearing_directory
echo ${MESSAGE} > usr/lib/keep_load_bearing_directory

# Package format: <target>-glibc-<version>-<date>.tar.xz
# Example: x86_64-linux-gnu-glibc-2.28-20241130.tar.xz
DATE=$(date +%Y%m%d)
PACKAGE_NAME="x86_64-linux-gnu-glibc-${GLIBC_VERSION}-${DATE}.tar.xz"

XZ_OPT=-e9 tar cJf "${ARTIFACTS_DIR}/${PACKAGE_NAME}" *

popd
