#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

pushd ${LLVM_DIR}

cp -r ${LLVM_SOURCE}/* .

export PATH=${GCC_BINS}:$PATH

cmake -G Ninja -S llvm -B build \
    -DLLVM_ENABLE_PROJECTS="clang;lld" \
    -DLIBCLANG_BUILD_STATIC=ON \
    -DLLVM_BUILD_STATIC=ON \
    -DLLVM_LINK_LLVM_DYLIB=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DLLVM_ENABLE_ZLIB=ON \
    -DCMAKE_C_COMPILER="${GCC_BINS}/x86_64-linux-musl-gcc" \
    -DCMAKE_CXX_COMPILER="${GCC_BINS}/x86_64-linux-musl-g++" \
    -DCMAKE_SYSROOT="${GCC_SYSROOT}" \
    -DCMAKE_EXE_LINKER_FLAGS="-static -s" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="${ARTIFACTS_DIR}" \
    -DLLVM_ENABLE_WARNINGS=OFF \
    -DCMAKE_SKIP_RPATH=TRUE


ninja -C build

ninja -C build install

popd

# Why CMAKE_SKIP_RPATH=TRUE? At install time I was getting this error.
# CMake Error at utils/TableGen/cmake_install.cmake:65 (file):
#   file RPATH_CHANGE could not write new RPATH:
#
#     $ORIGIN/../lib
#
#   to the file:
#
#     /tmp/artifacts/bin/llvm-tblgen
#
#   No valid ELF RPATH or RUNPATH entry exists in the file;
# Call Stack (most recent call first):
#   cmake_install.cmake:62 (include)
