#!/bin/bash
set -euox pipefail
source ${SCRIPTS_DIR}/environment

pushd ${ZLIB_DIR}

wget https://github.com/madler/zlib/releases/download/v${ZLIB_VERSION}/zlib-${ZLIB_VERSION}.tar.gz
tar -xzf zlib-${ZLIB_VERSION}.tar.gz --strip-components=1

export PATH=${GCC_BINS}:$PATH
export CC="${GCC_BINS}/x86_64-linux-musl-gcc"
export CXX="${GCC_BINS}/x86_64-linux-musl-g++"
export CFLAGS="-fPIC --sysroot=${GCC_SYSROOT}"
export CXXFLAGS="--sysroot=${GCC_SYSROOT}"

./configure --static --prefix=${GCC_SYSROOT}/usr
make
make install

popd
