name: Build LLVM/Clang on windows

on:
  workflow_dispatch:
    inputs:
      llvm_version:
        description: 'LLVM version to build'
        required: true
        default: '21.1.1'
        type: string

permissions:
  # Required for uploading GitHub releases
  contents: write
  # Required for build provenance attestation
  id-token: write
  attestations: write

env:
  LLVM_VERSION: ${{ github.event.inputs.llvm_version }}

jobs:
  build:
    runs-on: windows-11-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
      
      - name: Download llvm source
        run: |
          mkdir llvm-src
          curl -L -o llvm-project-${{ env.LLVM_VERSION }}.src.tar.xz https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ env.LLVM_VERSION }}/llvm-project-${{ env.LLVM_VERSION }}.src.tar.xz
          tar -xf llvm-project-${{ env.LLVM_VERSION }}.src.tar.xz -C llvm-src --strip-components=1

      - name: Build LLVM/Clang
        run: |
          cd llvm-src
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;lld" -DCMAKE_INSTALL_PREFIX=C:\LLVM ..\llvm
          ninja