name: Publish to BCR

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    outputs:
      release-tag: ${{ steps.create-tag.outputs.tag }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Create release tag
        id: create-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/workflows/create-release.sh

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: ${{ env.release_source_tarball }}

  publish:
    needs: create-release
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@main
    with:
      tag_name: ${{ needs.create-release.outputs.release-tag }}
      registry_fork: reutermj/bazel-central-registry
      attest: true
    permissions:
      contents: write
      id-token: write
      attestations: write
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
