name: Publish to BCR

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    outputs:
      release-tag: ${{ steps.create-tag.outputs.tag }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0

      - name: Create source tarball
        run: |
          DATE=$(grep -o 'version = "[^"]*"' MODULE.bazel | cut -d '"' -f 2 | head -n 1)
          SRC_TAR="toolchains_cc-$DATE.tar.gz"
          git archive --format=tar.gz --output=$SRC_TAR main
          echo "tag=$DATE" >> $GITHUB_OUTPUT
          echo "release_source_tarball=$SRC_TAR" >> $GITHUB_ENV

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: ${{ env.release_source_tarball }}

      - name: Download attestation
        run: |
          gh attestation download --repo reutermj/toolchains_cc ${{ env.release_source_tarball }} 
          ls
          mv ${{ env.release_source_tarball }}.jsonl ${{ env.release_source_tarball }}.intoto.jsonl || /bin/true

      - name: Create release tag
        id: create-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/workflows/create-release.sh

  publish:
    needs: create-release
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@main
    with:
      tag_name: ${{ needs.create-release.outputs.release-tag }}
      registry_fork: reutermj/bazel-central-registry
      attest: true
      tag_prefix: "" # defaults to "v"
    permissions:
      contents: write
      id-token: write
      attestations: write
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
