name: Bazel Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: build examples
      run: |
        cd examples/hello_world
        ../../bazel build --repo_env=ubuntu_cxx_std_lib=libstdc++ --repo_env=ubuntu_triple=x86_64-unknown-linux-gnu //...
        ../../bazel build --repo_env=ubuntu_cxx_std_lib=libc++ --repo_env=ubuntu_triple=x86_64-unknown-linux-gnu //...
        ../../bazel build --repo_env=ubuntu_cxx_std_lib=libstdc++ --repo_env=ubuntu_triple=x86_64-alpine-linux-musl //...
        ../../bazel build --repo_env=ubuntu_cxx_std_lib=libc++ --repo_env=ubuntu_triple=x86_64-alpine-linux-musl //...
